{% set name = "pyocse" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyocse-{{ version }}.tar.gz
  sha256: e976db10bf49e77741e3f274d6f66da34c8bf2c778bb035f5c86db26f0c4e4f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - pyocse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MaterSim/pyocse
  summary: Python Organic Crystal Simulation Environment
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
