{% set name = "pyocse" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyocse-{{ version }}.tar.gz
  sha256: e976db10bf49e77741e3f274d6f66da34c8bf2c778bb035f5c86db26f0c4e4f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - toml
    - xmltodict

test:
  imports:
    - pyocse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MaterSim/pyocse
  summary: Python Organic Crystal Simulation Environment
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
