{% set name = "pyocse" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyocse-{{ version }}.tar.gz
  sha256: c837ac595a374e46335df23935925ba3f7872f0a06bf835e1e10618eca81408f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - toml
    - xmltodict

test:
  imports:
    - pyocse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MaterSim/pyocse
  summary: Python Organic Crystal Simulation Environment
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
