schema_version: 1

context:
  name: pyocse
  version: "0.1.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: f531f6db7d78143f09bc37fe6b0c034de06206e1f68eb1472bcaf68de15af163

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - toml
    - xmltodict

tests:
  - python:
      imports:
        - pyocse
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Python Organic Crystal Simulation Environment
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/MaterSim/pyocse

extra:
  recipe-maintainers:
    - jan-janssen
